### ISSUE TITLE
protein tree testing: inconsistent polyprotein annotations

### ISSUE THREAD

**Issue by jgbaum** [IEDB/arborist#40]
It seems that polyproteins from some species include a breakdown of their final products and others do not.  E.g., 
![image](https://github.com/user-attachments/assets/17b8afcd-8acb-4ce6-abe7-e70670f8a837)

I imagine this is simply due to the annotations that are available for the record, but just listing it here in case it is something else.

**Comment by dmx2** [comment]
These examples are due to lack of annotations especially for proteins with ID pattern "A0A-" which are TrEMBL entries.

Closing this, but issue #46 covers the problem of annotating polyproteins that do have products with labels, which we are for now calling "mature protein", but this should be fixed.
